---
title: "Climate Change Report"
author: "Linn"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning =FALSE, message = FALSE)

library(tidyverse)
library(lubridate)
library(ggplot2)

#Average precipitation for each month in five year periods?
#Effect of temperature on percipitation from 2010 to 2020.
# Minimum and maxmum temperature over time for the entire period.
# Average tempt over time.
# what month has the most snowfall on average?

weather <- read_csv("sewanee_weather.csv")

names(weather)

tempt <- weather%>%
  select(TMAX,TMIN,DATE)%>%
  mutate(avg_tempt= (TMAX+TMIN)/2)

ggplot(data=tempt, aes(x=DATE , y=TMAX)) + geom_line()
ggplot(data=tempt, aes(x=DATE , y=TMIN)) + geom_jitter()

```
```{r}
# month has the most snowfall.

weather <- weather %>%
  mutate(month=month(ymd(DATE))) %>%
  mutate(year=year(ymd(DATE))) %>%
  mutate(month_name = month.abb[month]) %>%
  mutate(month_name=fct_reorder(month_name, month))
snow <- weather %>%
  select (SNOW,month_name) 
ggplot(data=snow, aes(x= month_name, y=SNOW)) + geom_col() + ylim(0,4)

```

```{r}
# Average tempt over time.

tempt <- weather%>%
  select(TMAX,TMIN,DATE,)%>%
  mutate(avg_tempt= (TMAX+TMIN)/2)


ggplot(data=tempt, aes(x=DATE , y=avg_tempt)) + geom_line()

```

```{r}
#how has snowfall changed over time for the entire period?

snow <-snow %>% 
  mutate(year= year(DATE))
ggplot(data= snow, aes(x=year, y=SNOW)) + geom_col() + ylim(0,4)
```
```{r}
#Average precipitation for each month in five year periods?


```

